/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GAbout {
    }
    interface GBlog {
    }
    interface GButton {
        "color": string;
        "href"?: string;
        "size": string;
        "type": string;
    }
    interface GCard {
    }
    interface GDrawer {
    }
    interface GFooter {
    }
    interface GHeader {
    }
    interface GHero {
    }
    interface GLine {
    }
    interface GList {
    }
    interface GModal {
    }
    interface GMotto {
    }
    interface GNav {
    }
    interface GNotify {
    }
    interface GPageNumber {
    }
    interface GPreNext {
    }
    interface GSearch {
    }
    interface GSummary {
    }
    interface GTags {
    }
}
declare global {
    interface HTMLGAboutElement extends Components.GAbout, HTMLStencilElement {
    }
    var HTMLGAboutElement: {
        prototype: HTMLGAboutElement;
        new (): HTMLGAboutElement;
    };
    interface HTMLGBlogElement extends Components.GBlog, HTMLStencilElement {
    }
    var HTMLGBlogElement: {
        prototype: HTMLGBlogElement;
        new (): HTMLGBlogElement;
    };
    interface HTMLGButtonElement extends Components.GButton, HTMLStencilElement {
    }
    var HTMLGButtonElement: {
        prototype: HTMLGButtonElement;
        new (): HTMLGButtonElement;
    };
    interface HTMLGCardElement extends Components.GCard, HTMLStencilElement {
    }
    var HTMLGCardElement: {
        prototype: HTMLGCardElement;
        new (): HTMLGCardElement;
    };
    interface HTMLGDrawerElement extends Components.GDrawer, HTMLStencilElement {
    }
    var HTMLGDrawerElement: {
        prototype: HTMLGDrawerElement;
        new (): HTMLGDrawerElement;
    };
    interface HTMLGFooterElement extends Components.GFooter, HTMLStencilElement {
    }
    var HTMLGFooterElement: {
        prototype: HTMLGFooterElement;
        new (): HTMLGFooterElement;
    };
    interface HTMLGHeaderElement extends Components.GHeader, HTMLStencilElement {
    }
    var HTMLGHeaderElement: {
        prototype: HTMLGHeaderElement;
        new (): HTMLGHeaderElement;
    };
    interface HTMLGHeroElement extends Components.GHero, HTMLStencilElement {
    }
    var HTMLGHeroElement: {
        prototype: HTMLGHeroElement;
        new (): HTMLGHeroElement;
    };
    interface HTMLGLineElement extends Components.GLine, HTMLStencilElement {
    }
    var HTMLGLineElement: {
        prototype: HTMLGLineElement;
        new (): HTMLGLineElement;
    };
    interface HTMLGListElement extends Components.GList, HTMLStencilElement {
    }
    var HTMLGListElement: {
        prototype: HTMLGListElement;
        new (): HTMLGListElement;
    };
    interface HTMLGModalElement extends Components.GModal, HTMLStencilElement {
    }
    var HTMLGModalElement: {
        prototype: HTMLGModalElement;
        new (): HTMLGModalElement;
    };
    interface HTMLGMottoElement extends Components.GMotto, HTMLStencilElement {
    }
    var HTMLGMottoElement: {
        prototype: HTMLGMottoElement;
        new (): HTMLGMottoElement;
    };
    interface HTMLGNavElement extends Components.GNav, HTMLStencilElement {
    }
    var HTMLGNavElement: {
        prototype: HTMLGNavElement;
        new (): HTMLGNavElement;
    };
    interface HTMLGNotifyElement extends Components.GNotify, HTMLStencilElement {
    }
    var HTMLGNotifyElement: {
        prototype: HTMLGNotifyElement;
        new (): HTMLGNotifyElement;
    };
    interface HTMLGPageNumberElement extends Components.GPageNumber, HTMLStencilElement {
    }
    var HTMLGPageNumberElement: {
        prototype: HTMLGPageNumberElement;
        new (): HTMLGPageNumberElement;
    };
    interface HTMLGPreNextElement extends Components.GPreNext, HTMLStencilElement {
    }
    var HTMLGPreNextElement: {
        prototype: HTMLGPreNextElement;
        new (): HTMLGPreNextElement;
    };
    interface HTMLGSearchElement extends Components.GSearch, HTMLStencilElement {
    }
    var HTMLGSearchElement: {
        prototype: HTMLGSearchElement;
        new (): HTMLGSearchElement;
    };
    interface HTMLGSummaryElement extends Components.GSummary, HTMLStencilElement {
    }
    var HTMLGSummaryElement: {
        prototype: HTMLGSummaryElement;
        new (): HTMLGSummaryElement;
    };
    interface HTMLGTagsElement extends Components.GTags, HTMLStencilElement {
    }
    var HTMLGTagsElement: {
        prototype: HTMLGTagsElement;
        new (): HTMLGTagsElement;
    };
    interface HTMLElementTagNameMap {
        "g-about": HTMLGAboutElement;
        "g-blog": HTMLGBlogElement;
        "g-button": HTMLGButtonElement;
        "g-card": HTMLGCardElement;
        "g-drawer": HTMLGDrawerElement;
        "g-footer": HTMLGFooterElement;
        "g-header": HTMLGHeaderElement;
        "g-hero": HTMLGHeroElement;
        "g-line": HTMLGLineElement;
        "g-list": HTMLGListElement;
        "g-modal": HTMLGModalElement;
        "g-motto": HTMLGMottoElement;
        "g-nav": HTMLGNavElement;
        "g-notify": HTMLGNotifyElement;
        "g-page-number": HTMLGPageNumberElement;
        "g-pre-next": HTMLGPreNextElement;
        "g-search": HTMLGSearchElement;
        "g-summary": HTMLGSummaryElement;
        "g-tags": HTMLGTagsElement;
    }
}
declare namespace LocalJSX {
    interface GAbout {
    }
    interface GBlog {
    }
    interface GButton {
        "color"?: string;
        "href"?: string;
        "size"?: string;
        "type"?: string;
    }
    interface GCard {
    }
    interface GDrawer {
    }
    interface GFooter {
    }
    interface GHeader {
    }
    interface GHero {
    }
    interface GLine {
    }
    interface GList {
    }
    interface GModal {
    }
    interface GMotto {
    }
    interface GNav {
    }
    interface GNotify {
    }
    interface GPageNumber {
    }
    interface GPreNext {
    }
    interface GSearch {
    }
    interface GSummary {
    }
    interface GTags {
    }
    interface IntrinsicElements {
        "g-about": GAbout;
        "g-blog": GBlog;
        "g-button": GButton;
        "g-card": GCard;
        "g-drawer": GDrawer;
        "g-footer": GFooter;
        "g-header": GHeader;
        "g-hero": GHero;
        "g-line": GLine;
        "g-list": GList;
        "g-modal": GModal;
        "g-motto": GMotto;
        "g-nav": GNav;
        "g-notify": GNotify;
        "g-page-number": GPageNumber;
        "g-pre-next": GPreNext;
        "g-search": GSearch;
        "g-summary": GSummary;
        "g-tags": GTags;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "g-about": LocalJSX.GAbout & JSXBase.HTMLAttributes<HTMLGAboutElement>;
            "g-blog": LocalJSX.GBlog & JSXBase.HTMLAttributes<HTMLGBlogElement>;
            "g-button": LocalJSX.GButton & JSXBase.HTMLAttributes<HTMLGButtonElement>;
            "g-card": LocalJSX.GCard & JSXBase.HTMLAttributes<HTMLGCardElement>;
            "g-drawer": LocalJSX.GDrawer & JSXBase.HTMLAttributes<HTMLGDrawerElement>;
            "g-footer": LocalJSX.GFooter & JSXBase.HTMLAttributes<HTMLGFooterElement>;
            "g-header": LocalJSX.GHeader & JSXBase.HTMLAttributes<HTMLGHeaderElement>;
            "g-hero": LocalJSX.GHero & JSXBase.HTMLAttributes<HTMLGHeroElement>;
            "g-line": LocalJSX.GLine & JSXBase.HTMLAttributes<HTMLGLineElement>;
            "g-list": LocalJSX.GList & JSXBase.HTMLAttributes<HTMLGListElement>;
            "g-modal": LocalJSX.GModal & JSXBase.HTMLAttributes<HTMLGModalElement>;
            "g-motto": LocalJSX.GMotto & JSXBase.HTMLAttributes<HTMLGMottoElement>;
            "g-nav": LocalJSX.GNav & JSXBase.HTMLAttributes<HTMLGNavElement>;
            "g-notify": LocalJSX.GNotify & JSXBase.HTMLAttributes<HTMLGNotifyElement>;
            "g-page-number": LocalJSX.GPageNumber & JSXBase.HTMLAttributes<HTMLGPageNumberElement>;
            "g-pre-next": LocalJSX.GPreNext & JSXBase.HTMLAttributes<HTMLGPreNextElement>;
            "g-search": LocalJSX.GSearch & JSXBase.HTMLAttributes<HTMLGSearchElement>;
            "g-summary": LocalJSX.GSummary & JSXBase.HTMLAttributes<HTMLGSummaryElement>;
            "g-tags": LocalJSX.GTags & JSXBase.HTMLAttributes<HTMLGTagsElement>;
        }
    }
}
